exclude: |
  ^application/static/|
  ^application/frontend/www/|
  ^application/static/assets/|
  ^node_modules/|
  ^dist/|
  ^build/|
  ^\.cache/|

repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

