doctype: CRE
id: 268-100
links:
- document:
    doctype: CRE
    id: 636-347
    name: HTTP security headers
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.4.6
    sectionID: Verify that a suitable Referrer-Policy header is included to avoid
      exposing sensitive information in the URL through the Referer header to untrusted
      parties.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/116.html
    name: CWE
    section: ''
    sectionID: '116'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Content Security Policy Cheat Sheet
  ltype: Linked To
name: Configure Referrer-Policy properly
