doctype: CRE
id: 110-531
links:
- document:
    doctype: CRE
    id: 177-260
    name: '>>Session management'
  ltype: Contains
- document:
    doctype: CRE
    id: 232-034
    name: Set '_Host' prefix for cookie-based session tokens
  ltype: Contains
- document:
    doctype: CRE
    id: 342-055
    name: Set "samesite" attribute for cookie-based session tokens
  ltype: Contains
- document:
    doctype: CRE
    id: 688-081
    name: Set "secure" attribute for cookie-based session tokens
  ltype: Contains
- document:
    doctype: CRE
    id: 705-182
    name: Set path attribute in cookie-bases session tokens as precise as possible
  ltype: Contains
- document:
    doctype: CRE
    id: 804-220
    name: Set httponly attribute for cookie-based session tokens
    tags:
    - XSS
  ltype: Contains
name: Cookie-config
