doctype: CRE
id: 208-355
links:
- document:
    doctype: CRE
    id: 473-177
    name: Deploy/build
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.4
    sectionID: Verify that the application, configuration, and all dependencies can
      be re-deployed using automated deployment scripts, built from a documented and
      tested runbook in a reasonable time, or restored from backups in a timely fashion.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
name: Ensure repeatability of deployment
