doctype: CRE
id: 558-807
links:
- document:
    doctype: CRE
    id: 270-568
    name: Authentication mechanism
  ltype: Contains
- document:
    doctype: CRE
    id: 228-551
    name: TLS
    tags:
    - Cryptography
  ltype: Related
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x11-V2-Authentication.md
    name: ASVS
    section: V2.2.5
    sectionID: Verify that where a Credential Service Provider (CSP) and the application
      verifying authentication are separated, mutually authenticated TLS is in place
      between the two endpoints.
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/319.html
    name: CWE
    section: ''
    sectionID: '319'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Authentication Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: Transport Layer Protection Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
    name: OWASP Cheat Sheets
    section: TLS Cipher String Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    name: NIST 800-63
    section: 5.2.6
  ltype: Linked To
name: Mutually authenticate application and credential service provider
