doctype: CRE
id: 530-671
links:
- document:
    doctype: CRE
    id: 634-733
    name: Communication authentication
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x10-V1-Architecture.md
    name: ASVS
    section: Verify that application components verify the authenticity of each side
      in a communication link to prevent person-in-the-middle attacks. For example,
      application components should validate TLS certificates and chains.
    sectionID: V1.9.2
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/295.html
    name: CWE
    section: ''
    sectionID: '295'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html
    name: Cheat_sheets
    section: Transport Layer Protection Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
    name: Cheat_sheets
    section: TLS Cipher String Cheat Sheet
  ltype: Linked To
name: Mutually authenticate application components
