doctype: CRE
id: 180-488
links:
- document:
    doctype: CRE
    id: 180-487
    name: Server protection
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x22-V14-Config.md
    name: ASVS
    section: V14.1.3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/16.html
    name: CWE
    section: '16'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html
    name: Cheat_sheets
    section: Docker Security Cheat Sheet
  ltype: Linked To
- document:
    description: '"Ensure that only POST is accepted where POST is expected."'
    doctype: Tool
    hyperlink: https://github.com/zaproxy/zap-extensions/blob/main/addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/GetForPostScanRule.java
    name: 'ZAP Rule: "GET for POST"'
    tags:
    - '10058'
    - '"Active"'
    tooltype: Offensive
  ltype: Linked To
name: Proper Configuration foe all applications and frameworks
