doctype: CRE
id: 527-034
links:
- document:
    doctype: CRE
    id: 435-702
    name: Communication encryption
    tags:
    - Cryptography
  ltype: Contains
- document:
    doctype: Standard
    hyperlink: https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/en/0x10-V1-Architecture.md
    name: ASVS
    section: V1.9.1
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://owasp-top-10-proactive-controls-2018.readthedocs.io/en/latest/c3-secure-database-access.html
    name: OWASP Proactive Controls
    section: C3
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cwe.mitre.org/data/definitions/319.html
    name: CWE
    section: '319'
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html
    name: Cheat_sheets
    section: Transport Layer Protection Cheat Sheet
  ltype: Linked To
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
    name: Cheat_sheets
    section: TLS Cipher String Cheat Sheet
  ltype: Linked To
name: Protect communication between application components
