doctype: CRE
id: 542-270
links:
- document:
    doctype: CRE
    id: 126-668
    name: '>>Secure data storage'
  ltype: Contains
- document:
    doctype: CRE
    id: 170-772
    name: Cryptography
  ltype: Related
- document:
    doctype: CRE
    id: 542-488
    name: Use cryptographically secure random number generators
  ltype: Contains
- document:
    doctype: CRE
    id: 664-571
    name: Ensure proper generation of secure random
  ltype: Contains
- document:
    doctype: CRE
    id: 027-210
    name: Create random GUIDs with cryptographically secure random number generators
  ltype: Contains
name: Secure random values
tags:
- Cryptography
