name: Sync
on:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
    - name: Setup
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      env: 
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_API_KEY: ${{ secrets.API_KEY }}
    - run: |
        
        ls -lah
        which pip
        
        mkdir -p ~/.ssh ~/.config/gspread
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/id_rsa

        
        cat ~/.ssh/id_rsa
        chmod 511 ~/.ssh/id_rsa
        
        sudo pip3 install -r scripts/cre_sync/requirements.txt 
      
        echo "$SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json
        cat ~/.config/gspread/service_account.json

        python3 scripts/cre_sync/spreadsheet_to_yaml.py
